<Project Sdk="Dalamud.NET.Sdk/15.0.0">

    <PropertyGroup>
        <TargetFramework>net10.0-windows7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AntiVirusScanner" Version="1.0.2" />
      <PackageReference Include="ECommons" Version="3.2.0.16" />
      <PackageReference Include="Glamourer.Api" Version="2.8.1" />
      <PackageReference Include="IpfsShipyard.Ipfs.Http.Client" Version="0.8.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
      <PackageReference Include="Penumbra.Api" Version="5.15.1" />
      <PackageReference Update="DalamudPackager" Version="15.0.0" />
      <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\HaselCommon\HaselCommon\HaselCommon.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="PocketSizedUniverse.json" />
    </ItemGroup>

    <ItemGroup>
      <None Include="EULA.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
